### PR TITLE
Rewrite the osc group command to be more user-friendly.

### PR DESCRIPTION
**Pull request by scarabeusiv**
As per summary this is first attempt to make the osc group friendly.

The only remaining are osc group approve and osc list <id> which need some work on obs side, so maybe bribing ancor with cookies could be sufficient.

### CODE REVIEW

**Comment by coolo** [comment]
maybe I misunderstand the usage function, but I like to 

```
osc group <pkg1> <pkg2>
```

and it autofinds if there is already a group to add either pkg1 or pkg2 to

**Comment by scarabeusiv** [comment]
Yea I was unsure how do that one clearly because I find more sane approach to do:

```
   osc group add <GROUP_ID> <packages>
```

Rather than:

```
   osc group add <somepackagewhichisingroup> <packages>
```

I think i could check if first argument is actually type group and then work as the <group_id> and otherwise group to first package that has some group id stored in itself?

Would that be sufficient?

**Comment by scarabeusiv** [comment]
It eat up content of my comment

osc group add groupID packages

osc group add package_which_is_in_group packages

**Comment by coolo** [comment]
I don't want to find out the groupID, all I want is to clue 2 packages together, so yes.

**Comment by scarabeusiv** [comment]
So this is how the adding looks like now with your feature

```
root@bugaboo: ~ # osc group add sqlite3 M17N:fonts
Checking if GR# is proper type...
Searching for SR#s based on the arguments...
Checking wether the SR#s are already in grouping project...
Added SR#196189 to group request GR#196531
Added SR#196490 to group request GR#196531

root@bugaboo: ~ # osc group remove 196531 M17N:fonts
Searching for SR#s based on the arguments...
Checking if GR# is proper type...
Checking wether the SR#s are already in grouping project...
Removed SR#196189 from group request GR#196531
Removed SR#196490 from group request GR#196531

root@bugaboo: ~ # osc group add 196531 M17N:fonts
Checking if GR# is proper type...
Searching for SR#s based on the arguments...
Checking wether the SR#s are already in grouping project...
Added SR#196189 to group request GR#196531
Added SR#196490 to group request GR#196531
```

**Pull request merged**
