### PR TITLE
Code cleanup and three bug fixed

### PR DESCRIPTION
**Pull request by aplanas**
-  Do review_status only for non-updated packages. If the package had changed the status ('ACCEPTED' or 'DECLINED') do not change again the status. This fix need more work, because there is a point where a package can be in 'UPDATED' status ('new') and after that can be 'ACCEPTED' or 'DECLINED'
- Different md5sum is now autodeclined. Requested by coolo
- Add a note for a suspicious case. If the package fails is in 'UPDATED' status instead 'DECLINED'. I think that this is a bug. Add a note but do not change the code.
- Bunch of Python normalization

### CODE REVIEW

**Comment by aplanas** [comment]
- Change the way to detect alldisabled SR: This is a bit risky. scarabeus has a complain in the ML for a declined SR. This showed a bug in the alldisabled detector. This variable was True when at least one repo was disabled, and looks like that this was not the original intention for this variable. Change this condition to foundsucceeded

**Comment by coolo** [comment]
only for noarch packages it's ok to build only on one arch, all other SRs need to build for everything.

**Comment by aplanas** [comment]
I will revert the change in this case

**Comment by aplanas** [comment]
Done

**Comment by coolo** [comment]
I rebased and also changed your XXX comment :)

**Pull request closed without merging**
